apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: applications
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: app1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: applications
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: diana1996/app1:latest
        ports:
        - containerPort: 8080
